# Generated by Django 4.2 on 2024-04-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avatar', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('FR', 'Free'), ('OC', 'Occupied')], default='FR', max_length=2)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='hotel.hotel')),
            ],
        ),
    ]
