# Generated by Django 4.2 on 2024-04-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="products/avatar"),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("FR", "Free"), ("OC", "Occupied"), ("IP", "In progress")],
                default="FR",
                max_length=2,
            ),
        ),
    ]
