# Generated by Django 4.2 on 2024-05-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_product_slug_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="Hammock", max_length=30),
        ),
    ]
