# Generated by Django 4.2 on 2024-04-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.CharField(choices=[('MOR', 'Morning'), ('AFT', 'Afternoon'), ('ALL', 'All Day')], max_length=3)),
                ('date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
