# Generated by Django 4.2 on 2024-04-26 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["date"]},
        ),
    ]
