# Generated by Django 4.2 on 2024-04-16 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='booking',
            managers=[
                ('paid_bookings', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.client'),
        ),
    ]
