# Generated by Django 4.2 on 2024-04-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("booking", "0002_alter_booking_options_alter_booking_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="products",
            field=models.ManyToManyField(to="product.product"),
        ),
    ]
