# Generated by Django 4.2 on 2024-05-01 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_booking_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="booking",
            managers=[],
        ),
    ]
