# Generated by Django 4.2 on 2024-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="hotel_client_id",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
