# Generated by Django 4.2 on 2024-03-18 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('booking', '0002_alter_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_client_remove_newuser_hotel_remove_newuser_user_ptr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
        migrations.AddField(
            model_name='client',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
