# Generated by Django 4.2 on 2024-03-27 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_client_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="num_guest",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ]
            ),
        ),
    ]
