# Generated by Django 4.2 on 2024-05-14 18:59

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="site_map",
        ),
        migrations.AddField(
            model_name="hotel",
            name="opening_afternoon_hours",
            field=models.CharField(
                default="14:00 - 19:00",
                max_length=20,
                validators=[hotel.models.validate_opening_hours],
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="opening_morning_hours",
            field=models.CharField(
                default="09:00 - 14:00",
                max_length=20,
                validators=[hotel.models.validate_opening_hours],
            ),
        ),
    ]
