# Generated by Django 4.2 on 2024-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="code",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
