# Generated by Django 4.2 on 2024-04-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_alter_hotel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="code",
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True
            ),
        ),
    ]
